package fingerprint

import "strings"

type ServiceFingerprint struct {
	ServiceName string
	Pattern     string
}

var serviceFingerprint = []ServiceFingerprint{
	{
		ServiceName: "S3 Bucket",
		Pattern:     "<Code>NoSuchBucket</Code>",
	},
	{
		ServiceName: "CloudFront",
		Pattern:     "Generated by cloudfront (CloudFront)",
	},
	{
		ServiceName: "GitHub Pages",
		Pattern:     "There isn't a GitHub Pages site here.",
	},
	{
		ServiceName: "Heroku",
		Pattern:     "//www.herokucdn.com/error-pages/no-such-app.html",
	},
	{
		ServiceName: "Azure Blob",
		Pattern:     "AccountNotEnabledForHTTP",
	},
	{
		ServiceName: "Azure Web App",
		Pattern:     "is not available in this Microsoft Azure App Service region",
	},
	{
		ServiceName: "Google Cloud Storage",
		Pattern:     "<Error><Code>NoSuchBucket</Code></Error>",
	},
	{
		ServiceName: "Google App Engine",
		Pattern:     "The requested URL / was not found on this server. That’s all we know.",
	},
	{
		ServiceName: "Shopify",
		Pattern:     "<p class=\"error\">Sorry, this shop is currently unavailable.</p>",
	},
	{
		ServiceName: "Squarespace",
		Pattern:     "If you're the owner of this website, please log in to your Squarespace account",
	},
}

func checkFingerprint(responseBody string) (bool, string) {
	for _, fingerprintn := range serviceFingerprint {
		if strings.Contains(responseBody, fingerprintn.Pattern) {
			return true, fingerprintn.ServiceName
		}
	}

	return false, ""
}
